FROM quay.io/centos-bootc/centos-bootc:stream10

COPY ./config/usr /usr

WORKDIR /tmp

COPY scripts scripts

RUN bash ./scripts/install-packages.bash

RUN bash ./scripts/download-binaries.bash && rm -rf *
