FROM quay.io/centos-bootc/centos-bootc:stream10

COPY ./config/usr /usr

RUN <<EOF
set -euo pipefail

dnf -y install epel-release
dnf -y install rsync fish qemu-guest-agent firewalld cockpit cockpit-podman cockpit-ostree unzip wget
dnf config-manager -y --add-repo https://pkgs.tailscale.com/stable/centos/10/tailscale.repo
dnf -y install tailscale
dnf config-manager -y --add-repo https://pkg.cloudflare.com/cloudflared-ascii.repo
dnf -y install cloudflared
dnf clean all
EOF

WORKDIR /tmp

COPY ./scripts/install-binaries.bash .

RUN bash ./install-binaries.bash && rm -rf *

RUN mkdir -p /usr/etc/systemd/system/multi-user.target.wants && \
    ln -s /usr/lib/systemd/system/tailscaled.service /usr/etc/systemd/system/multi-user.target.wants/tailscaled.service
