FROM quay.io/centos-bootc/centos-bootc:stream10

COPY config/usr /usr
RUN \
  ## Add vscode repo and key
  dnf -y install epel-release && \
  dnf -y install fish qemu-guest-agent firewalld && \
  dnf clean all
