- name: "Pull cloudflared image."
  containers.podman.podman_image:
    name: "{{ cloudflared_image }}"
    state: present

- name: Create container quadlet.
  containers.podman.podman_container:
    name: "{{ cloudflared_container_name }}"
    state: quadlet
    image: "{{ cloudflared_image }}"
    network: "host"
    secrets:
      - "cloudflared_tunnel_token,type=env,target=TUNNEL_TOKEN"
    command: "tunnel run"
    quadlet_filename: "{{ cloudflared_app_name }}"
    quadlet_options:
      - |
        [Unit]
        Description={{ cloudflared_app_name }} container
        ReloadPropagatedFrom={{ evilwoods_service_target }}
        StopPropagatedFrom={{ evilwoods_service_target }}
      - |
        [Service]
        EnvironmentFile={{ evilwoods_runner_home }}/.config/bws/env
        ExecStartPre=/usr/bin/bash -c "bws secret get {{ cloudflare_bw_token_id }} | jq -r '.value' | podman secret create --replace cloudflared_tunnel_token -"
      - |
        [Install]
        WantedBy={{ evilwoods_service_target }}
  notify: "Restart {{ cloudflared_app_name }}"
