- name: "Copy secret retrieval service for {{ cloudflared_app_name | upper }}"
  ansible.builtin.template:
    src: "{{ cloudflared_app_name }}-get-secret.service.j2"
    dest: "{{ evilwoods_unit_file_path }}/{{ cloudflared_app_name }}-get-secret.service"
    mode: "0644"
  notify: "Restart {{ cloudflared_service_name }}"

- name: "Pull cloudflared image."
  containers.podman.podman_image:
    name: "{{ cloudflared_image }}"
    state: present

- name: "Copy service quadlet file or {{ cloudflared_app_name | upper }}"
  ansible.builtin.template:
    src: "{{ cloudflared_app_name }}.container.j2"
    dest: "{{ evilwoods_quadlet_path }}/{{ cloudflared_app_name }}.container"
    mode: "0644"
  notify: Restart {{ cloudflared_service_name }}
