- name: Ensure required paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0775'
  loop:
    - "{{ evilwoods_authelia_quadlet_overrides_path }}"

- name: Render evilcloud network quadlet
  ansible.builtin.template:
    src: evilcloud.network.j2
    dest: "{{ evilwoods_quadlet_path }}/evilcloud.network"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0644'

- name: Render podman config file
  ansible.builtin.template:
    src: containers.conf.j2
    dest: "{{ common_containers_config_path }}/containers.conf"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0644'

- name: Enable podman auto update timer
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    state: started
    enabled: true
    scope: user
