evilwoods_runner_user: container-runner
evilwoods_runner_user_id: 1001
evilwoods_runner_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGFc8oFtu7i4WBlbcDMB7ua9cHJW2bzeomrLFddokw7v"
evilwoods_data_path: /var/lib/storage/data
evilwoods_quadlet_path: "{{ evilwoods_data_path }}/.config/containers/systemd"
evilwoods_runner_unit_file_path: "{{ evilwoods_data_path }}/.config/systemd/user"

evilwoods_domain_name: test.evilwoods.net

evilwoods_caddy_volume_path: "{{ evilwoods_data_path }}/caddy"
evilwoods_caddy_volume_config_path: "{{ evilwoods_caddy_volume_path }}/config"
evilwoods_caddy_volume_service_path: "{{ evilwoods_caddy_volume_config_path }}/services"
evilwoods_nextcloud_data_volume: "{{ evilwoods_data_path }}/nextcloud/data"

evilwoods_container_network: evilcloud
evilwoods_container_subnet_prefix: "10.200.0"
evilwoods_container_subnet: "{{ evilwoods_container_subnet_prefix }}.0/24"
evilwoods_container_gateway: "{{ evilwoods_container_subnet_prefix }}.1"
evilwoods_container_ip_range: "{{ evilwoods_container_subnet_prefix }}.100-{{ evilwoods_container_subnet_prefix }}.200"
evilwoods_caddy_ip: "{{ evilwoods_container_subnet_prefix }}.2"

# TODO: minimize hardcoded values in container names
evilwoods_container_name_prefix: quadlet-
