- name: "Pull fusion image."
  containers.podman.podman_image:
    name: "{{ fusion_image }}"
    state: present

- name: "Create volume quadlet."
  containers.podman.podman_volume:
    name: "{{ fusion_data_volume_name }}"
    state: quadlet
    quadlet_filename: "{{ fusion_data_volume_quadlet | splitext | first }}"

- name: "Render caddyfile for {{ fusion_app_name | upper }}"
  ansible.builtin.template:
    src: "{{ fusion_app_name }}.caddyfile.j2"
    dest: "{{ evilwoods_caddy_service_config }}/{{ fusion_app_name }}.caddyfile"
    mode: "0644"
  notify:
    - "Restart {{ evilwoods_caddy_service_name }}"

- name: "Create container quadlet."
  containers.podman.podman_container:
    name: "{{ fusion_container_name }}"
    state: quadlet
    image: "{{ fusion_image }}"
    volumes:
      - "{{ fusion_data_volume_quadlet }}:/data:Z,U"
    network: "{{ evilwoods_container_network_file }}"
    quadlet_filename: "{{ fusion_app_name }}"
    quadlet_options:
      - |
        [Unit]
        Description={{ fusion_app_name }} Container Service
        ReloadPropagatedFrom={{ evilwoods_service_target }}
        StopPropagatedFrom={{ evilwoods_service_target }}
      - |
        [Install]
        WantedBy={{ evilwoods_service_target }}
  notify:
    - "Restart {{ fusion_app_name }}"
