- name: Load host mount facts
  ansible.builtin.mount_facts:
  register: mount_facts
  failed_when: "'/var/home/crunner/storage' not in mount_facts.ansible_facts.mount_points"
  any_errors_fatal: true

- name: Ensure required paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0775'
  loop:
    - "{{ evilwoods_authelia_quadlet_overrides_path }}"
    - "{{ evilwoods_service_data_storage }}"

- name: Render evilcloud network quadlet
  ansible.builtin.template:
    src: evilcloud.network.j2
    dest: "{{ evilwoods_quadlet_path }}/evilcloud.network"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0644'

- name: Enable podman auto update timer
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    state: started
    enabled: true
    scope: user
