- name: Load host mount facts
  ansible.builtin.mount_facts:
  register: mount_facts
  failed_when: "'/var/home/crunner/storage' not in mount_facts.ansible_facts.mount_points"
  any_errors_fatal: true

- name: Ensure required paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0755'
  loop:
    - "{{ evilwoods_authelia_quadlet_overrides_d }}"
    - "{{ evilwoods_service_storage_d }}"
    - "{{ evilwoods_service_backup_d }}"
    - "{{ evilwoods_container_override_d }}"
    - "{{ common_script_d }}"

- name: Render evilcloud network quadlet
  ansible.builtin.template:
    src: evilcloud.network.j2
    dest: "{{ evilwoods_quadlet_path }}/evilcloud.network"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0644'

- name: Render systemd unit files.
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ evilwoods_unit_file_path }}/{{ item }}"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0644'
  loop:
    - "{{ evilwoods_service_target }}"
    - "common-restic-backup.service"
    - "common-restic-backup.timer"

- name: Render common restic backup scritps
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ common_script_d }}/{{ item }}"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0755'
  loop:
    - "{{ common_restic_backup_script | basename }}"
    - "{{ common_restic_backup_env_f | basename }}"

- name: Enable evilwoods target.
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
    daemon_reload: true
  loop:
    - "{{ evilwoods_service_target }}"
    - "common-restic-backup.timer"

- name: Render container common config.
  ansible.builtin.template:
    src: common-10-common.conf.j2
    dest: "{{ evilwoods_container_override_d }}/10-common.conf"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: '0644'

- name: Enable podman auto update timer
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    state: started
    enabled: true
    scope: user

# TODO: rename all quadlet files with prefix and implement common
# TODO: overrides shared by all evilcloud quadlets.
# TODO: For example, evilcloud-.container.d/10-overrides.conf and
# TODO: evilcloud-.pod.d/10-overrides.conf.
# TODO: Add options from kitchenowl to overrides.
