obsidian_sync_app_name: "obsidian-sync"
obsidian_sync_container_quadlet: "{{ obsidian_sync_app_name }}"
obsidian_sync_container_name: "{{ evilwoods_container_name_prefix }}{{ obsidian_sync_app_name }}"
obsidian_sync_service_name: "{{ obsidian_sync_app_name }}"
obsidian_sync_image: "docker.io/library/couchdb:3"
obsidian_sync_url: "ols.{{ evilwoods_domain_name }}"
obsidian_sync_data_d: "{{ evilwoods_service_storage_d }}/{{ obsidian_sync_app_name }}"
obsidian_sync_volume_d: "{{ obsidian_sync_data_d }}/volumes"
obsidian_sync_config_volume: "{{ obsidian_sync_volume_d }}/config"
obsidian_sync_data_volume: "{{ obsidian_sync_volume_d }}/data"
