- name: Restart caddy
  ansible.builtin.systemd:
    name: caddy.service
    state: restarted
    daemon_reload: true
    scope: user

- name: Restart authelia
  ansible.builtin.systemd:
    name: authelia-pod.service
    state: restarted
    daemon_reload: true
    scope: user
