- name: Ensure searxng volume directory exists
  ansible.builtin.file:
    path: "{{ searxng_volume_path }}"
    state: directory
    mode: "0755"

- name: Pull searxng image.
  containers.podman.podman_image:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ searxng_image }}"
    - "{{ searxng_valkey_image }}"

- name: Copy secret retrieval service file
  ansible.builtin.template:
    src: searxng-get-secrets.service.j2
    dest: "{{ evilwoods_unit_file_path }}/searxng-get-secrets.service"
    mode: "0644"
  notify:
    - "Restart {{ searxng_app_name }}-pod"

- name: Copy quadlet files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ evilwoods_quadlet_path }}/{{ item }}"
    mode: "0644"
  loop:
    - "{{ searxng_app_name }}-valkey.container"
    - "{{ searxng_app_name }}-valkey-data.volume"
    - "{{ searxng_app_name }}.pod"
    - "{{ searxng_app_name }}-server.container"
  notify:
    - "Restart {{ searxng_app_name }}-pod"

- name: Copy settings file to searxng volume
  ansible.builtin.template:
    src: "{{ searxng_app_name }}-settings.yml.j2"
    dest: "{{ searxng_volume_path }}/settings.yml"
    mode: "0644"
  notify: "Restart {{ searxng_app_name }}-pod"

- name: Copy searxng caddy config
  ansible.builtin.template:
    src: searxng.caddyfile.j2
    dest: "{{ evilwoods_caddy_service_config_path }}/searxng.caddyfile"
    mode: "0644"
  notify: "Restart {{ evilwoods_caddy_service_name }}"
