- name: "Ensure searxng volume directory exists"
  ansible.builtin.file:
    path: "{{ searxng_config_volume }}"
    state: directory
    mode: "0755"

- name: "Pull searxng images."
  containers.podman.podman_image:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ searxng_image }}"
    - "{{ searxng_valkey_image }}"

- name: "Copy settings file to searxng volume"
  become_method: containers.podman.podman_unshare
  become: true
  ansible.builtin.template:
    src: "{{ searxng_app_name }}-settings.yml.j2"
    dest: "{{ searxng_config_volume }}/settings.yml"
    mode: "0644"
  notify: "Restart {{ searxng_app_name }}-pod"

- name: "Render caddyfile."
  ansible.builtin.template:
    src: "searxng.caddyfile.j2"
    dest: "{{ evilwoods_caddy_service_config }}/searxng.caddyfile"
    mode: "0755"
  notify: "Restart {{ evilwoods_caddy_service_name }}"

- name: "Create pod quadlet."
  containers.podman.podman_pod:
    name: "{{ searxng_pod_name }}"
    state: quadlet
    network: "{{ evilwoods_container_network_file }}"
    quadlet_filename: "{{ searxng_pod_quadlet }}"
    quadlet_options:
      - |
        [Unit]
        Description=SearXNG Pod
        ReloadPropagatedFrom={{ evilwoods_service_target }}
        StopPropagatedFrom={{ evilwoods_service_target }}
      - |
        [Install]
        WantedBy={{ evilwoods_service_target }}
  notify:
    - "Restart {{ searxng_app_name }}-pod"

- name: "Create valkey data volume quadlet."
  containers.podman.podman_volume:
    name: "{{ searxng_valkey_data_volume_name }}"
    state: quadlet
    quadlet_filename: "{{ searxng_valkey_data_volume_quadlet }}"
  notify:
    - "Restart {{ searxng_app_name }}-pod"

- name: "Create valkey container quadlet."
  containers.podman.podman_container:
    name: "{{ searxng_valkey_container_name }}"
    state: quadlet
    image: "{{ searxng_valkey_image }}"
    volumes:
      - "{{ searxng_app_name }}-valkey-data.volume:/data:Z,U"
    pod: "{{ searxng_pod_quadlet }}"
    quadlet_filename: "{{ searxng_app_name }}-valkey"
    quadlet_options:
      - |
        [Unit]
        Description=Valkey Container Service
      - |
        [Service]
        Restart=always
  notify:
    - "Restart {{ searxng_app_name }}-pod"

- name: "Create searxng server container quadlet."
  containers.podman.podman_container:
    name: "{{ searxng_container_name }}"
    state: quadlet
    image: "{{ searxng_image }}"
    volumes:
      - "{{ searxng_config_volume }}:/etc/searxng:Z"
    secrets:
      - "{{ searxng_jwt_secret_name }},type=env,target=SEARXNG_SECRET"
    pod: "{{ searxng_pod_quadlet }}"
    quadlet_filename: "{{ searxng_container_quadlet }}"
    quadlet_options:
      - |
        [Unit]
        Description=SearXNG Container
        Wants={{ searxng_valkey_container_quadlet | splitext | first }}.service
        After={{ searxng_valkey_container_quadlet | splitext | first }}.service
      - |
        [Service]
        EnvironmentFile={{ evilwoods_runner_home }}/.config/bws/env
        ExecStartPre=/usr/bin/bash -c "bws secret get {{ searxng_jwt_secret_id }} | jq -r '.value' | podman secret create --replace {{ searxng_jwt_secret_name }} -"
  notify:
    - "Restart {{ searxng_app_name }}-pod"
