---
- name: Setup evilcloud server
  hosts: evilcloud
  remote_user: "{{ main_user }}"
  vars:
    main_user: aitvaras
    ansible_become_pass: "{{ main_user_password }}"
  roles:
    - role: container-runner
      become: true
      tags:
        - container-runner
    - role: cloudflared
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - cloudflared
    - role: caddy
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - caddy
    - role: searxng
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - searxng
    - role: ntfy
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - ntfy
    - role: kitchenowl
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - kitchenowl
    - role: immich
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - immich
    - role: nextcloud
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - nextcloud
