authelia_app_name: "{{ ansible_role_name}}"
authelia_container_name: "{{ evilwoods_container_name_prefix }}-{{ evilwoods_authelia_app_name }}"
authelia_service_name: "{{ authelia_app_name }}-pod"
authelia_pod_name: "{{ evilwoods_container_name_prefix }}-{{ authelia_app_name }}"
authelia_url: "auth.{{ evilwoods_domain_name }}"
authelia_get_secrets_service_name: "{{ authelia_app_name }}-get-secrets"
authelia_get_secrets_script_name: "{{ authelia_get_secrets_service_name }}.sh"

authelia_image: "docker.io/authelia/authelia:4.39"
authelia_valkey_image: "docker.io/valkey/valkey:8.1-alpine"
authelia_session_secret_name: "{{ authelia_app_name }}_session_secret"
authelia_storage_encryption_key_name: "{{ authelia_app_name }}_storage_encryption_key"
authelia_notifier_smtp_password_name: "{{ authelia_app_name }}_notifier_smtp_password"
authelia_oidc_hmac_secret_name: "{{ authelia_app_name }}_oidc_hmac_secret"
authelia_oidc_jwks_private_key_name: "{{ authelia_app_name }}_oidc_jwks_private_key"

authelia_volume_path: "{{ evilwoods_unnamed_volumes }}/{{ authelia_app_name }}"
# TODO put conpig files into subdirectory (config.d or something else). Adapt the whole role
authelia_config_volume: "{{ authelia_volume_path }}/config"
authelia_userdb_file: "user-database.yml"

authelia_env_filename: "env"
authelia_env_file: "{{ authelia_volume_path }}/{{ authelia_env_filename }}"
