- name: Pull image.
  containers.podman.podman_image:
    name: "{{ actual_image }}"
    state: present

- name: Create volume quadlet.
  containers.podman.podman_volume:
    name: "{{ actual_prefix }}{{ actual_data_volume }}"
    state: quadlet
    quadlet_filename: "{{ actual_data_volume }}"

- name: Render caddy config file
  ansible.builtin.template:
    src: "{{ actual_caddy_file }}.j2"
    dest: "{{ evilwoods_caddy_service_config_path }}/{{ actual_caddy_file }}"
    mode: "0644"
  notify: "Restart {{ evilwoods_caddy_service_name }}"

- name: Create container quadlet.
  containers.podman.podman_container:
    name: "{{ actual_container_name }}"
    state: quadlet
    image: "{{ actual_image }}"
    volumes:
      - "{{ actual_data_volume }}.volume:/data:Z"
    network: "{{ evilwoods_container_network_file }}"
    quadlet_filename: "{{ actual_app_name }}"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Unit]
        Description={{ actual_container_name }} service.
      - |
        [Install]
        WantedBy=default.target
  notify: "Restart {{ actual_container_name }}"
