- name: "Pull ntfy image."
  containers.podman.podman_image:
    name: "{{ ntfy_image }}"
    state: present

- name: "Render caddyfile."
  ansible.builtin.template:
    src: "{{ ntfy_app_name }}.caddyfile.j2"
    dest: "{{ evilwoods_caddy_service_config }}/{{ ntfy_app_name }}.caddyfile"
    mode: "0755"
  notify:
    - "Restart {{ evilwoods_caddy_service_name }}"

- name: "Create container quadlet."
  containers.podman.podman_container:
    name: "{{ ntfy_container_name }}"
    state: quadlet
    image: "{{ ntfy_image }}"
    command: ["serve"]
    network: "{{ evilwoods_container_network_file }}"
    quadlet_filename: "{{ ntfy_app_name }}"
    quadlet_options:
      - |
        [Unit]
        Description=ntfy service
        ReloadPropagatedFrom={{ evilwoods_service_target }}
        StopPropagatedFrom={{ evilwoods_service_target }}
        After=caddy.service
      - |
        [Install]
        WantedBy={{ evilwoods_service_target }}
  notify:
    - "Restart {{ ntfy_app_name }}"
