- name: Pull ntfy image.
  containers.podman.podman_image:
    name: "{{ ntfy_image }}"
    state: present

- name: "Copy quadlet file. {{ ntfy_app_name }}"
  ansible.builtin.template:
    src: "{{ ntfy_app_name }}.container.j2"
    dest: "{{ evilwoods_quadlet_path }}/{{ ntfy_app_name }}.container"
    mode: "0644"
  notify:
    - Restart {{ ntfy_app_name }}

- name: "Copy caddyfile. {{ ntfy_app_name }}"
  ansible.builtin.template:
    src: "{{ ntfy_app_name }}.caddyfile.j2"
    dest: "{{ evilwoods_caddy_service_config_path }}/{{ ntfy_app_name }}.caddyfile"
    mode: "0644"
  notify:
    - "Restart {{ evilwoods_caddy_service_name }}"
