- name: "Ensure paths exist for {{ immich_app_name }}"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: "0755"
  loop:
    # - "{{ immich_db_data_volume }}"
    - "{{ immich_upload_volume }}"
    - "{{ immich_config_volume }}"

- name: "Render configuration files for {{ immich_app_name }}"
  ansible.builtin.template:
    src: "immich.json.jinja"
    dest: "{{ immich_config_volume }}/immich.json"
    mode: "0644"

- name: "Render quadlet files for {{ immich_app_name }}"
  ansible.builtin.template:
    src: "{{ item }}.jinja"
    dest: "{{ evilwoods_quadlet_path }}/{{ item }}"
    mode: "0644"
  notify: Restart immich
  loop:
    - "immich.pod"
    - "immich-valkey-data.volume"
    - "immich-model-cache.volume"
    - "immich-valkey.container"
    - "immich-postgresql.container"
    - "immich-machine-learning.container"
    - "immich-server.container"

- name: "Render caddyfile for {{ immich_app_name }}"
  ansible.builtin.template:
    src: "immich.caddyfile.jinja"
    dest: "{{ evilwoods_caddy_volume_service_path }}/immich.caddyfile"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: "0644"
  notify: Restart caddy
