- name: "Copy quadlet file. {{ ntfy_app_name }}"
  ansible.builtin.template:
    src: "{{ ntfy_app_name }}.container.jinja"
    dest: "{{ evilwoods_quadlet_path }}/{{ ntfy_app_name }}.container"
    mode: "0644"
  notify:
    - Restart {{ ntfy_app_name }}

- name: "Copy caddyfile. {{ ntfy_app_name }}"
  ansible.builtin.template:
    src: "{{ ntfy_app_name }}.caddyfile.jinja"
    dest: "{{ evilwoods_caddy_volume_service_path }}/{{ ntfy_app_name }}.caddyfile"
    mode: "0644"
  notify:
    - Restart caddy
