- name: Add container runner user
  ansible.builtin.user:
    name: "{{ evilwoods_runner_user }}"
    home: "{{ evilwoods_data_path }}"
    shell: /usr/bin/bash
    create_home: true
    state: present

- name: Ensure storage directory exists
  ansible.builtin.file:
    path: "{{ evilwoods_data_path }}"
    state: directory
    mode: "0700"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"

- name: Ensure user systemd unit file dir exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: "0755"
  loop:
    - "{{ container_runner_unit_file_path }}"
    - "{{ container_runner_quadlet_path }}"
# SELinux context needs to be configured as user home directory.
# Otherwise, authorized_keys file will not be accessible.
# This copies the SELinux context from existing home directory to the storage directory.
- name: Configure SELinux context for storage directory
  community.general.sefcontext:
    target: "{{ evilwoods_data_path }}"
    substitute: "/var/home/aitvaras"
    state: present
  register: sefcontext_result
  notify:
    - Apply SELinux policy

- name: Add ssh key for container-runner user
  ansible.posix.authorized_key:
    user: "{{ evilwoods_runner_user }}"
    key: "{{ lookup('file', '/home/{{ main_user }}/.ssh/id_ed25519.pub') }}"
    state: present

- name: Check if linger is enabled for container-runner user
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ evilwoods_runner_user }}"
  register: linger_check

- name: Set linger for container-runner user
  ansible.builtin.file:
    path: "/var/lib/systemd/linger/{{ evilwoods_runner_user }}"
    state: touch
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
    mode: "0644"
  when: not linger_check.stat.exists

- name: Ensure container-runner user quadlet directory exists
  ansible.builtin.file:
    path: "{{ evilwoods_quadlet_path }}"
    state: directory
    mode: "0755"
    owner: "{{ evilwoods_runner_user }}"
    group: "{{ evilwoods_runner_user }}"
