- name: Ensure kischenowl required paths exist
  ansible.builtin.file:
    path: "{{ kitchenowl_volume_path }}"
    state: directory
    mode: "0775"

- name: Pull kitchenowl image.
  containers.podman.podman_image:
    name: "{{ kitchenowl_image }}"
    state: present

- name: Render kitchenowl quadlet file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ evilwoods_quadlet_path }}/{{ item }}"
    mode: "0644"
  notify: Restart kitchenowl
  loop:
    - "kitchenowl.container"
    - "kitchenowl-data.volume"

- name: Render kitchenowl authelia config
  ansible.builtin.template:
    src: kitchenowl-authelia-config.yml.j2
    dest: "{{ evilwoods_authelia_config_volume }}/kitchenowl-authelia-config.yml"
    mode: "0644"
  notify: Restart authelia

- name: Render authelia server quadlet overrides.
  ansible.builtin.template:
    src: kitchenowl-authelia-secrets.conf.j2
    dest: "{{ evilwoods_authelia_quadlet_overrides_path }}/kitchenowl-secrets.conf"
    mode: "0644"
  notify: Restart authelia

- name: Render kitchenowl secrets retrieval script.
  ansible.builtin.template:
    src: kitchenowl-get-secrets.sh.j2
    dest: "{{ kitchenowl_get_secrets_script }}"
    mode: "0774"
  notify: Restart kitchenowl

- name: Render kitchenowl caddyfile
  ansible.builtin.template:
    src: kitchenowl.caddyfile.j2
    dest: "{{ evilwoods_caddy_service_config_path }}/kitchenowl.caddyfile"
    mode: "0644"
  notify: Restart caddy
