- name: Ensure kischenowl required paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ kitchenowl_data_volume }}"
    - "{{ kitchenowl_script_dir }}"

- name: Pull kitchenowl image.
  containers.podman.podman_image:
    name: "{{ kitchenowl_image }}"
    state: present

- name: Create kitchenowl container quadlet
  containers.podman.podman_container:
    name: "{{ kitchenowl_container_name }}"
    state: quadlet
    image: "{{ kitchenowl_image }}"
    env:
      FRONT_URL: "https://{{ kitchenowl_url }}"
      OIDC_ISSUER: "https://{{ evilwoods_oidc_issuer }}"
    secrets:
      - "{{ kitchenowl_jwt_secret_name }},type=env,target=JWT_SECRET_KEY"
      - "{{ kitchenowl_oidc_client_name }},type=env,target=OIDC_CLIENT_ID"
      - "{{ kitchenowl_oidc_client_secret_name }},type=env,target=OIDC_CLIENT_SECRET"
    network:
      - "{{ evilwoods_container_network_file }}"
    volumes:
      - "{{ kitchenowl_data_volume }}:/data:Z"
    quadlet_filename: "{{ kitchenowl_container_quadlet }}"
    quadlet_options:
      - "AddHost={{ evilwoods_authelia_url }}:{{ evilwoods_caddy_ip }}"
      - |
        [Unit]
        Description={{ kitchenowl_app_name }} container service.
        ReloadPropagatedFrom={{ evilwoods_service_target }}
        StopPropagatedFrom={{ evilwoods_service_target }}
      - |
        [Service]
        EnvironmentFile={{ evilwoods_runner_home }}/.config/bws/env
        ExecStartPre={{ kitchenowl_get_secrets_script }}
      - |
        [Install]
        WantedBy={{ evilwoods_service_target }}

- name: Render oidc client config
  ansible.builtin.blockinfile:
    path: "{{ evilwoods_authelia_client_config_f }}"
    marker: "{{ kitchenowl_oidc_client_config_marker }}"
    block: "{{ lookup('template', 'kitchenowl-authelia-config.yml.j2') | indent(width=6, first=True) }}"
  notify: Restart authelia

- name: Render authelia server quadlet overrides.
  ansible.builtin.template:
    src: kitchenowl-authelia-secrets.conf.j2
    dest: "{{ evilwoods_authelia_quadlet_overrides_d }}/kitchenowl-secrets.conf"
    mode: "0644"
  notify: Restart authelia

- name: Render kitchenowl secrets retrieval script.
  ansible.builtin.template:
    src: "{{ kitchenowl_get_secrets_script_name }}.j2"
    dest: "{{ kitchenowl_get_secrets_script }}"
    mode: "0774"
  notify: Restart kitchenowl

- name: Render kitchenowl caddyfile
  ansible.builtin.template:
    src: kitchenowl.caddyfile.j2
    dest: "{{ evilwoods_caddy_service_config }}/kitchenowl.caddyfile"
    mode: "0644"
  notify: Restart caddy
