- name: "Ensure paths exist for {{ immich_app_name }}"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
  loop:
    - "{{ immich_config_volume }}"

- name: "Render configuration files for {{ immich_app_name }}"
  ansible.builtin.template:
    src: "{{ immich_settings_file }}.j2"
    dest: "{{ immich_config_volume }}/{{ immich_settings_file }}"
    mode: "0644"

- name: "Render quadlet files for {{ immich_app_name }}"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ evilwoods_quadlet_path }}/{{ item }}"
    mode: "0644"
  notify: Restart immich
  loop:
    - "immich.pod"
    - "{{ immich_valkey_volume }}"
    - "{{ immich_postgresql_volume }}"
    - "{{ immich_model_cache_volume }}"
    - "{{ immich_uploads_volume }}"
    - "immich-valkey.container"
    - "immich-postgresql.container"
    - "immich-machine-learning.container"
    - "immich-server.container"

- name: "Render caddyfile for {{ immich_app_name }}"
  ansible.builtin.template:
    src: "immich.caddyfile.j2"
    dest: "{{ evilwoods_caddy_service_config_path }}/immich.caddyfile"
    mode: "0644"
  notify: Restart caddy
