- name: "Create configuration directory for {{ caddy_app_name | upper }}"
  ansible.builtin.file:
    path: "{{ evilwoods_caddy_volume_service_path }}"
    state: directory
    mode: "0755"

- name: "Copy configuration file for {{ caddy_app_name | upper }}"
  ansible.builtin.copy:
    src: "Caddyfile"
    dest: "{{ evilwoods_caddy_volume_config_path }}/Caddyfile"
    mode: "0644"
  notify: Restart caddy

- name: "Copy global configuration file for {{ caddy_app_name | upper }}"
  ansible.builtin.template:
    src: "global.caddyfile.jinja"
    dest: "{{ evilwoods_caddy_volume_config_path }}/global.caddyfile"
    mode: "0644"
  notify: Restart caddy

- name: "Copy service quadlet file for {{ caddy_app_name | upper }}"
  ansible.builtin.template:
    src: "caddy.container.jinja"
    dest: "{{ evilwoods_quadlet_path }}/caddy.container"
    mode: "0644"
  notify: Restart caddy

- name: "Copy data volume file for {{ caddy_app_name | upper }}"
  ansible.builtin.template:
    src: "caddy_data.volume.jinja"
    dest: "{{ evilwoods_quadlet_path }}/caddy_data.volume"
    mode: "0644"
  notify: Restart caddy
