- name: Render kitchenowl quadlet file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ evilwoods_quadlet_path }}/{{ item }}"
    mode: "0644"
  notify: Restart kitchenowl
  loop:
    - "kitchenowl.container"
    - "kitchenowl-data.volume"

- name: Render kitchenowl secret retrieval unit file
  ansible.builtin.template:
    src: kitchenowl-get-secrets.service.j2
    dest: "{{ evilwoods_unit_file_path }}/kitchenowl-get-secrets.service"
    mode: "0644"
  notify: Restart kitchenowl

- name: Render kitchenowl caddyfile
  ansible.builtin.template:
    src: kitchenowl.caddyfile.j2
    dest: "{{ evilwoods_caddy_service_config_path }}/kitchenowl.caddyfile"
    mode: "0644"
  notify: Restart caddy
