---
- name: Setup evilcloud server
  hosts: evilcloud
  remote_user: "{{ main_user }}"
  vars:
    main_user: aitvaras
    ansible_become_pass: "{{ main_user_password }}"
  roles:
    - role: crunner
      become: true
      tags:
        - crunner
    - role: common
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - common
    - role: cloudflared
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - cloudflared
        - roles
    - role: caddy
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - caddy
        - roles
    - role: authelia
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - authelia
        - roles
    - role: searxng
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - searxng
        - roles
    - role: ntfy
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - ntfy
        - roles
    - role: kitchenowl
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - kitchenowl
        - roles
    - role: fusion
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - fusion
        - roles
    - role: actual
      become_user: "{{ evilwoods_runner_user }}"
      become: true
      tags:
        - actual
        - roles
