- name: "Pull app image."
  containers.podman.podman_image:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ authelia_image }}"
    - "{{ authelia_valkey_image }}"

- name: "Ensure config path exists."
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ authelia_config_dir }}"
    - "{{ authelia_script_dir }}"

- name: "Render get-secrets script."
  ansible.builtin.template:
    src: "{{ authelia_get_secrets_script }}.j2"
    dest: "{{ authelia_script_dir }}/{{ authelia_get_secrets_script }}"
    mode: "0755"
  notify:
    - "Restart {{ authelia_app_name }}"

- name: "Render environment file."
  ansible.builtin.template:
    src: "authelia-env.j2"
    dest: "{{ authelia_env_file }}"
    mode: "0644"
  notify:
    - "Restart {{ authelia_app_name }}"

- name: "Render userdb files."
  ansible.builtin.template:
    src: "{{ authelia_app_name }}-{{ item }}.j2"
    dest: "{{ authelia_config_volume }}/{{ item }}"
    mode: "0644"
  loop:
    - "{{ authelia_userdb_file }}"
  notify:
    - "Restart {{ authelia_app_name }}"

- name: "Render config files."
  ansible.builtin.template:
    src: "{{ authelia_app_name }}-{{ item }}.j2"
    dest: "{{ authelia_config_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - "configuration.yml"
  notify:
    - "Restart {{ authelia_app_name }}"

- name: "Create oidc client config file"
  ansible.builtin.blockinfile:
    path: "{{ evilwoods_authelia_client_config_f }}"
    create: true
    insertbefore: BOF
    block: |
      identity_providers:
        oidc:
          clients:
    mode: "0644"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: "Render caddy config file."
  ansible.builtin.template:
    src: "{{ authelia_app_name }}.caddyfile.j2"
    dest: "{{ evilwoods_caddy_service_config }}/{{ authelia_app_name }}.caddyfile"
    mode: "0755"
  notify:
    - "Restart {{ evilwoods_caddy_service_name }}"

- name: "Create pod quadlet."
  containers.podman.podman_pod:
    name: "{{ authelia_pod_name }}"
    state: quadlet
    network: "{{ evilwoods_container_network_file }}"
    quadlet_filename: "{{ authelia_pod_quadlet }}"
    quadlet_options:
      - |
        [Unit]
        Description={{ authelia_app_name }} pod service.
        ReloadPropagatedFrom={{ evilwoods_service_target }}
        StopPropagatedFrom={{ evilwoods_service_target }}
        [Service]
        Restart=on-failure
        [Install]
        WantedBy={{ evilwoods_service_target }}
  notify:
    - "Restart {{ authelia_app_name }}"

- name: "Create valkey data volume quadlet."
  containers.podman.podman_volume:
    name: "{{ authelia_valkey_data_volume_name }}"
    state: quadlet
    quadlet_filename: "{{ authelia_valkey_data_volume_quadlet }}"
  notify:
    - "Restart {{ authelia_app_name }}"

- name: "Create authelia valkey container quadlet file."
  containers.podman.podman_container:
    name: "{{ authelia_valkey_container_name }}"
    state: quadlet
    image: "{{ authelia_valkey_image }}"
    volumes:
      - "{{ authelia_valkey_data_volume_quadlet }}:/data"
    pod: "{{ authelia_pod_quadlet }}"
    quadlet_filename: "{{ authelia_valkey_container_quadlet }}"
    quadlet_options:
      - |
        [Unit]
        Description={{ authelia_app_name }} valkey container.
        [Service]
        Restart=on-failure
  notify:
    - "Restart {{ authelia_app_name }}"

- name: "Create authelia container quadlet file."
  containers.podman.podman_container:
    name: "{{ authelia_container_name }}"
    state: quadlet
    image: "{{ authelia_image }}"
    env_file: "{{ authelia_env_file }}"
    volumes:
      - "{{ authelia_config_volume }}:/config:Z"
    secrets:
      - "{{ authelia_session_secret_name }}"
      - "{{ authelia_storage_encryption_key_name }}"
      - "{{ authelia_notifier_smtp_password_name }}"
      - "{{ authelia_oidc_hmac_secret_name }}"
      - "{{ authelia_oidc_jwks_private_key_name }}"
    pod: "{{ authelia_pod_quadlet }}"
    quadlet_filename: "{{ authelia_container_quadlet }}"
    quadlet_options:
      - |
        [Unit]
        Description={{ authelia_app_name }} container.
      - |
        [Service]
        EnvironmentFile={{ evilwoods_runner_home }}/.config/bws/env
        ExecStartPre={{ authelia_script_dir }}/{{ authelia_get_secrets_script }}
  notify:
    - "Restart {{ authelia_app_name }}"
