- name: "Create configuration directory for {{ caddy_app_name | upper }}"
  ansible.builtin.file:
    path: "{{ evilwoods_caddy_service_config_path }}"
    state: directory
    mode: "0755"

- name: "Pull caddy image."
  containers.podman.podman_image:
    name: "{{ caddy_image }}"
    state: present

- name: "Copy configuration file for {{ caddy_app_name | upper }}"
  ansible.builtin.copy:
    src: "Caddyfile"
    dest: "{{ evilwoods_caddy_config_volume }}/Caddyfile"
    mode: "0644"
  notify: "Restart {{ caddy_app_name }}"

- name: "Copy global configuration file for {{ caddy_app_name | upper }}"
  ansible.builtin.template:
    src: "global.caddyfile.j2"
    dest: "{{ evilwoods_caddy_config_volume }}/global.caddyfile"
    mode: "0644"
  notify: "Restart {{ caddy_app_name }}"

- name: "Create data volume quadlet."
  containers.podman.podman_volume:
    name: "{{ caddy_data_volume_name }}"
    state: quadlet
    quadlet_filename: "{{ caddy_data_volume_quadlet }}"
  notify: "Restart {{ caddy_app_name }}"

- name: "Create container quadlet."
  containers.podman.podman_container:
    name: "{{ caddy_container_name }}"
    state: quadlet
    image: "{{ caddy_image }}"
    network: "{{ evilwoods_container_network_file }}"
    volumes:
      - "{{ evilwoods_caddy_config_volume }}:/etc/caddy:Z"
      - "{{ caddy_data_volume_quadlet }}:/data:Z"
    publish:
      - "8080:80"
      - "8443:443"
    ip: "{{ evilwoods_caddy_ip }}"
    quadlet_filename: "{{ caddy_app_name }}"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Unit]
        Description={{ caddy_app_name }} service.
        Wants=cloudflared.service
        After=cloudflared.service
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
  notify: "Restart {{ caddy_app_name }}"
