searxng_app_name: "{{ ansible_role_name }}"
searxng_pod_name: "{{ evilwoods_container_name_prefix }}-{{ searxng_app_name }}"
searxng_service_name: "{{ searxng_app_name }}"
searxng_valkey_name: "{{ evilwoods_container_name_prefix }}-{{ searxng_app_name }}-valkey"
searxng_image: "docker.io/searxng/searxng:latest"
searxng_valkey_image: "docker.io/valkey/valkey:8.1-alpine"
searxng_port: "{{ Evilwoods_server_port }}"
searxng_volume_path: "{{ evilwoods_unnamed_volumes }}/{{ searxng_app_name }}"
searxng_url: "search.{{ evilwoods_domain_name }}"
searxng_jwt_secret_name: "{{ searxng_app_name }}_jwt_secret"
