evilwoods_authelia_app_name: "authelia"
evilwoods_authelia_url: "auth.{{ evilwoods_domain_name }}"
evilwoods_authelia_container_name: "{{ evilwoods_container_name_prefix }}{{ evilwoods_authelia_app_name }}"
evilwoods_authelia_quadlet_overrides_path: "{{ evilwoods_quadlet_path }}/authelia-server.container.d"
evilwoods_authelia_data: "{{ evilwoods_service_data_storage }}/{{ evilwoods_authelia_app_name }}"
evilwoods_authelia_volume_dir: "{{ evilwoods_authelia_data }}/volumes"
evilwoods_authelia_config_volume: "{{ evilwoods_authelia_volume_dir }}/config"
evilwoods_authelia_config_dir: "{{ evilwoods_authelia_config_volume }}/configuration"
