evilwoods_runner_user: crunner
evilwoods_runner_home: "/var/home/{{ evilwoods_runner_user }}"
evilwoods_storage_d: "{{ evilwoods_runner_home }}/storage"
evilwoods_service_storage_d: "{{ evilwoods_storage_d }}/services"
evilwoods_service_backup_d: "{{ evilwoods_storage_d }}/backups"
evilwoods_volumes: "{{ evilwoods_data_path }}/volumes"
evilwoods_quadlet_path: "{{ evilwoods_runner_home }}/.config/containers/systemd"
evilwoods_unit_file_path: "{{ evilwoods_runner_home }}/.config/systemd/user"
evilwoods_runner_bw_config_path: "{{ evilwoods_runner_home }}/.config/bws"
evilwoods_container_name_prefix: quadlet-
evilwoods_domain_name: "{{ evilcloud_domain }}"
evilwoods_container_network_name: evilcloud
evilwoods_container_network_file: "{{ evilwoods_container_network_name }}.network"
evilwoods_container_subnet_prefix: "10.200.0"
evilwoods_container_subnet: "{{ evilwoods_container_subnet_prefix }}.0/24"
evilwoods_container_gateway: "{{ evilwoods_container_subnet_prefix }}.1"
evilwoods_container_ip_range: "{{ evilwoods_container_subnet_prefix }}.100-{{ evilwoods_container_subnet_prefix }}.200"
evilwoods_oidc_issuer: "auth.{{ evilcloud_domain }}"

# TODO: minimize hardcoded values in container names

evilwoods_nextcloud_volume: "nextcloud.volume"
evilwoods_nextcloud_data_volume: "{{ evilwoods_data_path }}/nextcloud/data"

evilwoods_podman_secrets_path: "/run/secrets"

evilwoods_service_target: "evilcloud.target"

evilwoods_container_override_d: "{{ evilwoods_quadlet_path }}/container.d"
