- name: Ensure searxng data directory exists
  ansible.builtin.file:
    path: "{{ searxng_data_path }}"
    state: directory
    mode: "0755"

- name: Copy secret retrieval service file
  ansible.builtin.template:
    src: searxng-get-secrets.service.j2
    dest: "{{ evilwoods_runner_unit_file_path }}/searxng-get-secrets.service"
    mode: "0644"
  notify:
    - Restart searxng-pod

- name: Copy Valkey quadlet
  ansible.builtin.template:
    src: searxng-valkey.container.j2
    dest: "{{ evilwoods_quadlet_path }}/valkey.container"
    mode: "0644"
  notify:
    - Restart searxng-pod

- name: Copy valkey volume quadlet
  ansible.builtin.template:
    src: searxng-valkey-data.volume.j2
    dest: "{{ evilwoods_quadlet_path }}/valkey_data.volume"
    mode: "0644"
  notify:
    - Restart searxng-pod

- name: Copy settings file to searxng volume
  ansible.builtin.template:
    src: settings.yml.j2
    dest: "{{ searxng_data_path }}/settings.yml"
    mode: "0644"
  notify: Restart searxng-pod

- name: Copy searxng pod file
  ansible.builtin.template:
    src: searxng.pod.j2
    dest: "{{ evilwoods_quadlet_path }}/searxng.pod"
    mode: "0644"
  notify: Restart searxng-pod

- name: Copy searxng container file
  ansible.builtin.template:
    src: searxng.container.j2
    dest: "{{ evilwoods_quadlet_path }}/searxng.container"
    mode: "0644"
  notify: Restart searxng-pod

- name: Copy searxng caddy config
  ansible.builtin.template:
    src: searxng.caddyfile.j2
    dest: "{{ evilwoods_caddy_volume_service_path }}/searxng.caddyfile"
    mode: "0644"
  notify: Restart caddy
