name: build-evilwoods-desktop
on:
  schedule:
    - cron: "41 4 * * *"
  push:
    branches: ["main"]
    paths:
      - "bootc/evilwoods-desktop/**"
  workflow_dispatch:

jobs:
  podman-build:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/evilwoods-common.yml
    with:
      num-packages-to-keep: 20
      image-name: "evilwoods-desktop"
      containerfile-name: "workflow.Containerfile"
      cache-rpms: true
      extra-args: "--volume /tmp/libdnf5/:/var/cache/libdnf5:z"
    secrets: inherit
