name: build-evilwoods-server
on:
  schedule:
    - cron: "21 4 * * 5"
  push:
    branches: ["main"]
    paths:
      - "bootc/evilwoods-server/**"
  workflow_dispatch:

jobs:
  podman-build:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/evilwoods-common.yml
    with:
      num-packages-to-keep: 20
      image-name: "evilwoods-server"
