name: build-evilwoods-desktop
on:
  schedule:
    - cron: "41 4 * * *"
  push:
    branches: [$default-branch]
    paths:
      - "bootc/evilwoods-desktop/**"
  workflow_dispatch:
    inputs:
      skip-cache:
        description: "No cache"
        type: boolean
        default: false

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: evilwoods-desktop
  CONTAINERFILE: workflow.Containerfile

jobs:
  podman-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/build-container-image
        with:
          container-repository: ${{ env.REGISTRY }}
          image-name: ${{ env.IMAGE_NAME }}
          containerfile: ${{ env.CONTAINERFILE }}
          skip-cache: ${{ github.event.inputs.no-cache }}
          setup-layer-caching: "true"
          setup-rpm-caching: "true"
          cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
          cosign-password: ${{ secrets.COSIGN_PASSWORD }}
          num-packages-to-keep: 20
