name: build-evilwoods-binary-cache
on:
  push:
    branches: [$default-branch]
    paths:
      - "bootc/evilwoods-binary-cache/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: evilwoods-binary-cache
  CONTAINERFILE: workflow.Containerfile

jobs:
  podman-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/build-container-image
        with:
          container-repository: ${{ env.REGISTRY }}
          image-name: ${{ env.IMAGE_NAME }}
          containerfile: ${{ env.CONTAINERFILE }}
          cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
          cosign-password: ${{ secrets.COSIGN_PASSWORD }}
