name: build-evilwoods-server
on:
  schedule:
    - cron: "21 4 * * 5"
  push:
    branches: ["main"]
    paths:
      - "evilwoods-server/bootc/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "evilwoods-server"
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  podman-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2.13
        with:
          context: "./evilwoods-server/bootc"
          containerfiles: "./evilwoods-server/bootc/Containerfile"
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          layers: false
          oci: true

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
